### ISSUE TITLE
Crypto becomes the hell in browserify

### ISSUE THREAD

**Issue by nicola** [rdfjs-base/normalize#2]
When I browserify crypto, this imports a huge amount of unnecessary dependencies, how can we avoid this?

See: `/Users/mozilla/Proj/gits/simplerdf/node_modules/rdf-ext/node_modules/rdf-graph-array/node_modules/rdf-graph-abstract/node_modules/rdf-normalize/jsonld-normalize.js`

**Comment by nicola** [comment]
@bergos ^

**Comment by bergos** [comment]
fixed in #4
